franka_lock_unlock_node:
  ros__parameters:
    hostname: "localhost"
    username: "user" # Replace with the Username
    password: "strongpwd" # Replace with your password
    enable_relock: True # Relock the brakes on exit
    wait_web_ui: True # Wait in case the robot web UI is currently in use
    request_physical_access: True # Request control by confirming physical access to the robot in case the robot web UI is currently in use
    enable_fci: True # Activate the FCI
    # home_gripper: True # Home the gripper # TODO(Sachin): Implement this param in future
    robot_type: "fr3" # options: fr3, panda
